//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CitasAppXamarin.com.somee.citasapp {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CitasWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CitasWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegistrarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_User_IdOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Horas_Disponibles_FechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Tipos_ServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_ServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgendarCitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Marcar_OcupadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Marcar_DisponibleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CitasWebService() {
            this.Url = "http://citasapp.somee.com/CitasWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistrarClienteCompletedEventHandler RegistrarClienteCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Get_User_IdCompletedEventHandler Get_User_IdCompleted;
        
        /// <remarks/>
        public event Get_Horas_Disponibles_FechaCompletedEventHandler Get_Horas_Disponibles_FechaCompleted;
        
        /// <remarks/>
        public event Get_Tipos_ServicioCompletedEventHandler Get_Tipos_ServicioCompleted;
        
        /// <remarks/>
        public event Get_ServiciosCompletedEventHandler Get_ServiciosCompleted;
        
        /// <remarks/>
        public event AgendarCitaCompletedEventHandler AgendarCitaCompleted;
        
        /// <remarks/>
        public event Marcar_OcupadoCompletedEventHandler Marcar_OcupadoCompleted;
        
        /// <remarks/>
        public event Marcar_DisponibleCompletedEventHandler Marcar_DisponibleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RegistrarCliente(string nombre, string apellido, string correo, string telefono, short edad, string contraseña) {
            object[] results = this.Invoke("RegistrarCliente", new object[] {
                        nombre,
                        apellido,
                        correo,
                        telefono,
                        edad,
                        contraseña});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string nombre, string apellido, string correo, string telefono, short edad, string contraseña) {
            this.RegistrarClienteAsync(nombre, apellido, correo, telefono, edad, contraseña, null);
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string nombre, string apellido, string correo, string telefono, short edad, string contraseña, object userState) {
            if ((this.RegistrarClienteOperationCompleted == null)) {
                this.RegistrarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarClienteOperationCompleted);
            }
            this.InvokeAsync("RegistrarCliente", new object[] {
                        nombre,
                        apellido,
                        correo,
                        telefono,
                        edad,
                        contraseña}, this.RegistrarClienteOperationCompleted, userState);
        }
        
        private void OnRegistrarClienteOperationCompleted(object arg) {
            if ((this.RegistrarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarClienteCompleted(this, new RegistrarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Login(string correo, string contra) {
            object[] results = this.Invoke("Login", new object[] {
                        correo,
                        contra});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string correo, string contra) {
            this.LoginAsync(correo, contra, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string correo, string contra, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        correo,
                        contra}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_User_Id", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Get_User_Id(string email) {
            object[] results = this.Invoke("Get_User_Id", new object[] {
                        email});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Get_User_IdAsync(string email) {
            this.Get_User_IdAsync(email, null);
        }
        
        /// <remarks/>
        public void Get_User_IdAsync(string email, object userState) {
            if ((this.Get_User_IdOperationCompleted == null)) {
                this.Get_User_IdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_User_IdOperationCompleted);
            }
            this.InvokeAsync("Get_User_Id", new object[] {
                        email}, this.Get_User_IdOperationCompleted, userState);
        }
        
        private void OnGet_User_IdOperationCompleted(object arg) {
            if ((this.Get_User_IdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_User_IdCompleted(this, new Get_User_IdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Horas_Disponibles_Fecha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetalleDia[] Get_Horas_Disponibles_Fecha(int mes, int dia) {
            object[] results = this.Invoke("Get_Horas_Disponibles_Fecha", new object[] {
                        mes,
                        dia});
            return ((DetalleDia[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Horas_Disponibles_FechaAsync(int mes, int dia) {
            this.Get_Horas_Disponibles_FechaAsync(mes, dia, null);
        }
        
        /// <remarks/>
        public void Get_Horas_Disponibles_FechaAsync(int mes, int dia, object userState) {
            if ((this.Get_Horas_Disponibles_FechaOperationCompleted == null)) {
                this.Get_Horas_Disponibles_FechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Horas_Disponibles_FechaOperationCompleted);
            }
            this.InvokeAsync("Get_Horas_Disponibles_Fecha", new object[] {
                        mes,
                        dia}, this.Get_Horas_Disponibles_FechaOperationCompleted, userState);
        }
        
        private void OnGet_Horas_Disponibles_FechaOperationCompleted(object arg) {
            if ((this.Get_Horas_Disponibles_FechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Horas_Disponibles_FechaCompleted(this, new Get_Horas_Disponibles_FechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Tipos_Servicio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tipos_Servicio[] Get_Tipos_Servicio() {
            object[] results = this.Invoke("Get_Tipos_Servicio", new object[0]);
            return ((Tipos_Servicio[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_Tipos_ServicioAsync() {
            this.Get_Tipos_ServicioAsync(null);
        }
        
        /// <remarks/>
        public void Get_Tipos_ServicioAsync(object userState) {
            if ((this.Get_Tipos_ServicioOperationCompleted == null)) {
                this.Get_Tipos_ServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Tipos_ServicioOperationCompleted);
            }
            this.InvokeAsync("Get_Tipos_Servicio", new object[0], this.Get_Tipos_ServicioOperationCompleted, userState);
        }
        
        private void OnGet_Tipos_ServicioOperationCompleted(object arg) {
            if ((this.Get_Tipos_ServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Tipos_ServicioCompleted(this, new Get_Tipos_ServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Servicios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Servicios[] Get_Servicios(int TipoServicioId) {
            object[] results = this.Invoke("Get_Servicios", new object[] {
                        TipoServicioId});
            return ((Servicios[])(results[0]));
        }
        
        /// <remarks/>
        public void Get_ServiciosAsync(int TipoServicioId) {
            this.Get_ServiciosAsync(TipoServicioId, null);
        }
        
        /// <remarks/>
        public void Get_ServiciosAsync(int TipoServicioId, object userState) {
            if ((this.Get_ServiciosOperationCompleted == null)) {
                this.Get_ServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_ServiciosOperationCompleted);
            }
            this.InvokeAsync("Get_Servicios", new object[] {
                        TipoServicioId}, this.Get_ServiciosOperationCompleted, userState);
        }
        
        private void OnGet_ServiciosOperationCompleted(object arg) {
            if ((this.Get_ServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_ServiciosCompleted(this, new Get_ServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgendarCita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgendarCita(string descripcion, string numero_deposito, int Servicio_Id, int Cliente_Id, int DetalleFechaBloque_Id) {
            object[] results = this.Invoke("AgendarCita", new object[] {
                        descripcion,
                        numero_deposito,
                        Servicio_Id,
                        Cliente_Id,
                        DetalleFechaBloque_Id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgendarCitaAsync(string descripcion, string numero_deposito, int Servicio_Id, int Cliente_Id, int DetalleFechaBloque_Id) {
            this.AgendarCitaAsync(descripcion, numero_deposito, Servicio_Id, Cliente_Id, DetalleFechaBloque_Id, null);
        }
        
        /// <remarks/>
        public void AgendarCitaAsync(string descripcion, string numero_deposito, int Servicio_Id, int Cliente_Id, int DetalleFechaBloque_Id, object userState) {
            if ((this.AgendarCitaOperationCompleted == null)) {
                this.AgendarCitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgendarCitaOperationCompleted);
            }
            this.InvokeAsync("AgendarCita", new object[] {
                        descripcion,
                        numero_deposito,
                        Servicio_Id,
                        Cliente_Id,
                        DetalleFechaBloque_Id}, this.AgendarCitaOperationCompleted, userState);
        }
        
        private void OnAgendarCitaOperationCompleted(object arg) {
            if ((this.AgendarCitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgendarCitaCompleted(this, new AgendarCitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Marcar_Ocupado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Marcar_Ocupado(int Id_Detalle_Dia) {
            object[] results = this.Invoke("Marcar_Ocupado", new object[] {
                        Id_Detalle_Dia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Marcar_OcupadoAsync(int Id_Detalle_Dia) {
            this.Marcar_OcupadoAsync(Id_Detalle_Dia, null);
        }
        
        /// <remarks/>
        public void Marcar_OcupadoAsync(int Id_Detalle_Dia, object userState) {
            if ((this.Marcar_OcupadoOperationCompleted == null)) {
                this.Marcar_OcupadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcar_OcupadoOperationCompleted);
            }
            this.InvokeAsync("Marcar_Ocupado", new object[] {
                        Id_Detalle_Dia}, this.Marcar_OcupadoOperationCompleted, userState);
        }
        
        private void OnMarcar_OcupadoOperationCompleted(object arg) {
            if ((this.Marcar_OcupadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Marcar_OcupadoCompleted(this, new Marcar_OcupadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Marcar_Disponible", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Marcar_Disponible(int Id_Detalle_Dia) {
            object[] results = this.Invoke("Marcar_Disponible", new object[] {
                        Id_Detalle_Dia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Marcar_DisponibleAsync(int Id_Detalle_Dia) {
            this.Marcar_DisponibleAsync(Id_Detalle_Dia, null);
        }
        
        /// <remarks/>
        public void Marcar_DisponibleAsync(int Id_Detalle_Dia, object userState) {
            if ((this.Marcar_DisponibleOperationCompleted == null)) {
                this.Marcar_DisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcar_DisponibleOperationCompleted);
            }
            this.InvokeAsync("Marcar_Disponible", new object[] {
                        Id_Detalle_Dia}, this.Marcar_DisponibleOperationCompleted, userState);
        }
        
        private void OnMarcar_DisponibleOperationCompleted(object arg) {
            if ((this.Marcar_DisponibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Marcar_DisponibleCompleted(this, new Marcar_DisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleDia {
        
        private int idField;
        
        private int horaIdField;
        
        private string bloqueField;
        
        private int fechaIdField;
        
        private short mesField;
        
        private short diaField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int HoraId {
            get {
                return this.horaIdField;
            }
            set {
                this.horaIdField = value;
            }
        }
        
        /// <remarks/>
        public string Bloque {
            get {
                return this.bloqueField;
            }
            set {
                this.bloqueField = value;
            }
        }
        
        /// <remarks/>
        public int FechaId {
            get {
                return this.fechaIdField;
            }
            set {
                this.fechaIdField = value;
            }
        }
        
        /// <remarks/>
        public short Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        public short Dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Servicios {
        
        private int idField;
        
        private string nombreField;
        
        private int tipoServicio_IdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int TipoServicio_Id {
            get {
                return this.tipoServicio_IdField;
            }
            set {
                this.tipoServicio_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tipos_Servicio {
        
        private int idField;
        
        private string descripcionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void RegistrarClienteCompletedEventHandler(object sender, RegistrarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_User_IdCompletedEventHandler(object sender, Get_User_IdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_User_IdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_User_IdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Horas_Disponibles_FechaCompletedEventHandler(object sender, Get_Horas_Disponibles_FechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Horas_Disponibles_FechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Horas_Disponibles_FechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetalleDia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetalleDia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_Tipos_ServicioCompletedEventHandler(object sender, Get_Tipos_ServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Tipos_ServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Tipos_ServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tipos_Servicio[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tipos_Servicio[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Get_ServiciosCompletedEventHandler(object sender, Get_ServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_ServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_ServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servicios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servicios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void AgendarCitaCompletedEventHandler(object sender, AgendarCitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgendarCitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgendarCitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Marcar_OcupadoCompletedEventHandler(object sender, Marcar_OcupadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Marcar_OcupadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Marcar_OcupadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Marcar_DisponibleCompletedEventHandler(object sender, Marcar_DisponibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Marcar_DisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Marcar_DisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591